version: '3'
services:
  db:
    image: postgres
  nginx:
    image: nginx:1.12.1
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    ports:
      - "80:80"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start"
    volumes:
      - .:/deployr
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db

